FROM work_env
RUN apt-get update && apt-get upgrade -y
RUN apt-get install -y openssh-server
RUN mkdir /var/run/sshd \
    && echo 'root:root' | chpasswd \
    && sed 's/#*PermitRootLogin prohibit-password/PermitRootLogin yes/' -i /etc/ssh/sshd_config \
    && sed 's/session\s*required\s*pam_loginuid.so/session optional pam_loginuid.so/' -i /etc/pam.d/sshd

EXPOSE 22
EXPOSE 2222

ENTRYPOINT ["/usr/sbin/sshd", "-D"]